# -*- coding: utf-8 -*-
"""TF_IDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o8l1lrVtrt6irCHhb_sOsYeNYaEDIi_N
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense,TextVectorization

text=np.array(["I like Java", "She dislikes AI", "He loves DAA", "AI is boring"])
label=np.array([1,0,1,0])

vector= TextVectorization(output_mode="tf_idf")
vector.adapt(text)

model = Sequential([vector, Dense(16, activation="relu"), Dense(1,activation="sigmoid")])
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])
model.fit(tf.constant(text, dtype=tf.string), label, epochs=20)

testData = np.array(["I like DAA"],dtype=object)
predScore=model.predict(testData)
print("Accuracy Scores", predScore)

if predScore > 0.5:
  print("Label : 1")
else:
  print("Label : 0")

testSent=np.array(["He likes NLP", "She dislikes AI"],dtype=object)
predTestData=model.predict(testSent)
print("Accuracy Scores", predTestData)
for t,p in zip(testSent, predTestData):
  if p>0.5:
    print("Label : 1")
  else:
    print("Label : 0")