# -*- coding: utf-8 -*-
"""TF_IDF_Multiclass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DjsawgiPNZcYuZOsY88iRDdsxx7ISyJx
"""

import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer


from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

# Load data
df = pd.read_csv('/content/namescodeA.csv')

# Input & Output
X = df["Name"]
Y = df["Country_code"].values
print(Y)

# Encode labels
label_encoder = LabelEncoder()
Y = label_encoder.fit_transform(Y)
# print(Y)
# print(np.unique(Y))
Y = to_categorical(Y)

# Text → TF-IDF
token = Tokenizer()
token.fit_on_texts(X)
X = token.texts_to_matrix(X, mode="tfidf")

# Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

# Model
model = Sequential([
    Dense(8, activation='relu', input_shape=(X.shape[1],)),
    Dense(64, activation='relu'),
    Dense(Y.shape[1], activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=60)

loss, accuracy = model.evaluate(X_test, Y_test)
print("Test Accuracy:", accuracy)

# Confusion Matrix
pred = model.predict(X_test)
Y_pred = np.argmax(pred, axis=1)
Y_true = np.argmax(Y_test, axis=1)

print(confusion_matrix(Y_true, Y_pred))

# Example Prediction - Not Required
sample_name = ["Fahmy Al Kharafi"]

sample_vector = token.texts_to_matrix(sample_name, mode="tfidf")

prediction = model.predict(sample_vector)

predicted_class = np.argmax(prediction)

predicted_label = label_encoder.inverse_transform([predicted_class])

print("\nPredicted Country Code:", predicted_label[0])