# -*- coding: utf-8 -*-
"""EXP9 Word2vec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gt4d8pOy5fIV2RYNpPOET8haiKm7teLU
"""

!pip install gensim
import nltk
from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec

text=["king is a brave man", "king is a kind man","queen is beautiful woman", "rose is red", "milk is white", "chennai is a city in tamilnadu", "mumbai is a city in maharahtra"]

nltk.download('punkt_tab')

corpus=[word_tokenize(sentence.lower()) for sentence in text]
print(corpus)

model=Word2Vec(sentences=corpus,vector_size=2, window=2, min_count=1, sg=0) #1 skipgram, 0 = CBOW)
# Word Embedding Example
print("Word Embedding of King", model.wv["king"])
print("Word Embedding of Queen", model.wv["queen"])

print(model.wv.most_similar("king"))

print(model.wv.similarity("king","queen"))
dwp=model.wv.most_similar(["king","queen"],["red"])
print(dwp)

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

words=list(model.wv.index_to_key)
result=model.wv[words]
for i,word in enumerate(corpus):
	plt.scatter(result[i,0], result[i,1])
	plt.text(result[i,0], result[i,1], word)
plt.show()

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

words=list(model.wv.index_to_key)
vectors=model.wv[words]


pca=PCA(n_components=2)

result=pca.fit_transform(vectors)

for i,word in enumerate(words):
	plt.scatter(result[i,0], result[i,1])
	plt.text(result[i,0], result[i,1], word)
plt.show()

