# -*- coding: utf-8 -*-
"""Chi-Square.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHdlru5kqXiwrFZyRs9ktJ-_Rea3HOUQ
"""

import nltk
import math
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

text = "She knocked the door many people knocked at the door many people knocked door a man knocked front door he knocked Tyson 's door he knocked door once in a while i knocked door for so many times knocked door exists"
w1 = "knocked"
w2 = "door"

tokens = word_tokenize(text)
stop_words = set(stopwords.words('english'))

words = [word.lower() for word in tokens if word.lower() not in stop_words]
print("Filtered Words:", words)

bigrams = []

for i in range(len(words)-1):
    bigrams.append(words[i] + " " + words[i+1])

N = len(bigrams)

w1_count = words.count(w1)
w2_count = words.count(w2)
bigram_count = bigrams.count(w1 + " " + w2)

print("Bigram Count:", bigram_count)
print("Bigrams :", bigrams)

A = B = C = D = 0

for bg in bigrams:
    x, y = bg.split()

    if x == w1 and y == w2:
        A += 1
    elif x == w1 and y != w2:
        B += 1
    elif x != w1 and y == w2:
        C += 1
    else:
        D += 1

print("A:", A, "B:", B, "C:", C, "D:", D)

E_A = (A + B) * (A + C) / N
E_B = (A + B) * (B + D) / N
E_C = (C + D) * (A + C) / N
E_D = (C + D) * (B + D) / N

chi = ((A - E_A)**2 / E_A) + \
      ((B - E_B)**2 / E_B) + \
      ((C - E_C)**2 / E_C) + \
      ((D - E_D)**2 / E_D)

print("Chi-square value:", round(chi, 2))

if chi > 3.84:
    print("Collocated")
else:
    print("Not Collocated")

