# -*- coding: utf-8 -*-
"""T-Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yHdlru5kqXiwrFZyRs9ktJ-_Rea3HOUQ
"""

import nltk
import math
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

text = "She knocked the door many people knocked at the door many people knocked door a man knocked front door he knocked Tyson 's door he knocked door once in a while i knocked door for so many times knocked door exists"
w1 = "knocked"
w2 = "door"

tokens = word_tokenize(text)
stop_words = set(stopwords.words('english'))

words = [word.lower() for word in tokens if word.lower() not in stop_words]
print("Filtered Words:", words)

bigrams = []

for i in range(len(words)-1):
    bigrams.append(words[i] + " " + words[i+1])

N = len(bigrams)

w1_count = words.count(w1)
w2_count = words.count(w2)
bigram_count = bigrams.count(w1 + " " + w2)

print("Bigram Count:", bigram_count)
print("Bigrams :", bigrams)

p1 = w1_count / N
p2 = w2_count / N
p12 = bigram_count / N

mue = p1 * p2

if p12 != 0:
    t_value = (p12 - mue) / math.sqrt(p12 / N)
else:
    t_value = 0

print("T-test value:", round(t_value, 2))

if t_value > 1.645:
    print("Collocated")
else:
    print("Not Collocated")

