# -*- coding: utf-8 -*-
"""PCFG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FkhiSUsvE6xSpy3p5LG5XzIOzbPXvZsW
"""

import numpy as np

def cyk(pcfg,tokens):
  n = len(tokens)
  nt = pcfg["non_terminals"]
  nt_idx = { name : i for i , name in enumerate(nt)}
  num_nt = len(nt)

  table = np.zeros((n,n,num_nt))

  for i,word in enumerate(tokens):
    for lhs,ter,prob in pcfg["lexicon"]:
      if ter == word:
        table[i][i][nt_idx[lhs]] += prob

  for length in range(2,n+1):
    for i in range(n-length+1):
      j = i+length-1
      for k in range(i,j):
        for lhs,b,c,prob in pcfg["rules"]:
          p_bc = prob * table[i][k][nt_idx[b]] * table[k+1][j][nt_idx[c]]
          table[i][j][nt_idx[lhs]] += p_bc
  return table

grammar = {
 'non_terminals': ['S', 'NP', 'VP', 'PP', 'P', 'V'],
 'rules': [
 ('S', 'NP', 'VP', 1.0),
 ('PP', 'P', 'NP', 1.0),
 ('VP', 'V', 'NP', 0.7),
 ('VP', 'VP', 'PP', 0.3),
 ('NP', 'NP', 'PP', 0.4)
 ],
 'lexicon': [
 ('P', 'with', 1.0),
 ('NP', 'astronomers', 0.1),
 ('NP', 'ears', 0.18),
 ('NP', 'saw', 0.04),
 ('NP', 'stars', 0.18),
 ('NP', 'telescopes', 0.1),
 ('V', 'saw', 1.0)
 ]
}

sentence = ["astronomers", "saw", "stars", "with", "ears"]

prob = cyk(grammar,sentence)
final_prob = prob[0][len(sentence)-1][0]
print(f"Final Prob : {final_prob:.7f}")

