# -*- coding: utf-8 -*-
"""LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1owEGu6V_q3vVBxMLY9vllLgWALZTv2jN
"""

import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Dropout,LSTM
from keras.callbacks import ModelCheckpoint
from keras.utils import to_categorical
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt_tab')

file=open("/content/Pizza.txt").read()

words=word_tokenize(file)
#words=file
words = ' '.join(words)
chars=sorted(list(set(words)))
char_to_num=dict((c,i) for i,c in enumerate(chars))

input_len=len(words)
vocab_len=len(chars)
seq_length=100

x_data=[]
y_data=[]

for i in range(0,input_len -seq_length,1):
  in_seq=words[i:i+seq_length]
  out_seq=words[i+seq_length]
  x_data.append([char_to_num[char] for char in in_seq])
  y_data.append(char_to_num[out_seq])

n_patterns=len(x_data)
x=np.reshape(x_data,(n_patterns,seq_length,1))
x=x/float(vocab_len)
y=to_categorical(y_data)

model = Sequential()

model.add(LSTM(256, input_shape=(x.shape[1],x.shape[2]), return_sequences=True))
model.add(Dropout(0.2))

model.add(LSTM(256,return_sequences=True))
model.add(Dropout(0.2))

model.add(LSTM(128))
model.add(Dropout(0.2))

model.add(Dense(y.shape[1],activation="softmax"))
model.compile(loss="categorical_crossentropy",optimizer="adam")

desired_callbacks = [ ModelCheckpoint( filepath="bestLSTM.h5",       monitor="val_loss", save_best_only = True) ]

model.fit(x,y,epochs=4,batch_size = 256, callbacks = desired_callbacks)

num_to_char = dict((i,c) for i,c in enumerate(chars))
start = np.random.randint(0,len(x_data)-1)
pattern = x_data[start]
print("random : ..","".join(num_to_char[v] for v in pattern))
print(len(pattern))