# -*- coding: utf-8 -*-
"""LSTM Text Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-1kiNrjAN7DDQP8nSrAx2FpjV7b6QSY
"""

import numpy as np
from keras.models import Sequential
from keras.utils import to_categorical
from keras.layers import Embedding,LSTM ,Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

text = open("/content/Pizza.txt", "r", encoding="utf-8").read()

token = Tokenizer()
token.fit_on_texts([text])
total_words = len(token.word_index) + 1
print(total_words)

seq = []

for line in text.split('.'):
  token_list = token.texts_to_sequences([line])[0]

  for i in range(1, len(token_list)):
    n_gram_sequence = token_list[:i+1]
    seq.append(n_gram_sequence)

max_sequence_len = max([len(x) for x in seq])
seq = np.array(pad_sequences(seq, maxlen=max_sequence_len, padding='pre'))
X = seq[:, :-1]
Y = seq[:, -1]

Y = to_categorical(Y, num_classes=total_words)

model = Sequential()

model.add(Embedding(total_words, 64, input_length=max_sequence_len-1))
model.add(LSTM(100))
model.add(Dense(total_words, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=100, verbose=1)

def generate_text(seed_text, next_words, max_sequence_len):
  for _ in range(next_words):
    token_list = token.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')

    predicted = np.argmax(model.predict(token_list), axis=-1)[0]
    predicted_word = token.index_word[predicted]

    seed_text += " " + predicted_word
  return seed_text


print(generate_text("Virtual reality and augmented reality", 10, max_sequence_len))

