# -*- coding: utf-8 -*-
"""Hindle Rooth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kNUqjyeHWLmS7rrJFQIgJ57YfL0DPg9R
"""

import nltk
from collections import defaultdict
from nltk import word_tokenize , pos_tag

verb_prep_count = defaultdict(int)
noun_prep_count = defaultdict(int)
verb_count = defaultdict(int)
noun_count = defaultdict(int)

def extract_pairs(sentence):
    words = word_tokenize(sentence)
    tags = pos_tag(words)

    verb = None
    noun = None
    for word, tag in tags:

        if tag.startswith('V'):
            verb = word.lower()
            verb_count[verb] += 1

        elif tag.startswith('N'):
            noun = word.lower()
            noun_count[noun] += 1

        elif tag == 'IN':
            prep = word.lower()

            if verb:
                verb_prep_count[(verb, prep)] += 1
            if noun:
                noun_prep_count[(noun, prep)] += 1

import nltk
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

def hindle_rooth_decision(sentence):

    words = nltk.word_tokenize(sentence)
    tags = nltk.pos_tag(words)

    verb = None
    noun = None
    prep = None

    for word, tag in tags:
        if tag.startswith('V'):
            verb = word.lower()

        elif tag.startswith('N'):
            noun = word.lower()

        elif tag == 'IN':
            prep = word.lower()

    if not (verb and noun and prep):
        return "Insufficient data"

    # Probabilities
    pv = verb_prep_count[(verb, prep)] / (verb_count[verb] + 1e-6)
    pn = noun_prep_count[(noun, prep)] / (noun_count[noun] + 1e-6)


    print(f"\nSentence: {sentence}")
    print(f"Verb = {verb}")
    print(f"Noun = {noun}")
    print(f"Preposition = {prep}")
    print(f"P(prep|verb) = {round(pv)}")
    print(f"P(prep|noun) = {pn}")

    if pv > pn:
        return "Preposition attached to VERB"
    else:
        return "Preposition attached to NOUN"

# Training corpus
corpus = [
    "I ate pizza with a fork",
    "She saw the man with a telescope",
    "He cut the bread with a knife",
    "They watched birds in the park",
    "She decorated cake with cream",
    "He opened the box with a key"
]

import math
# Training
for sent in corpus:
    extract_pairs(sent)

# Test sentences
test_sentence1 = "She saw the snake in the box"
test_sentence2 = "He cut the bread with a fork"

print("Decision:", hindle_rooth_decision(test_sentence1))
print("Decision:", hindle_rooth_decision(test_sentence2))

