# -*- coding: utf-8 -*-
"""EXp11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18n0fDxkXLvhU4dtvJQWBNoqAIUIYQiES
"""

import tensorflow as tf
import numpy as np
from string import punctuation
from keras.models import Sequential
from keras.layers import Embedding, LSTM, Dense
from keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences

# ---------------------------
# LOAD DATASET
# ---------------------------
source = []
target = []

try:
    lines =  open('Tamil Dataset.txt', 'r', encoding='utf-8').read().split('\n')

    for line in lines:
        if line.strip() == "":
            continue

        # Split using TAB (English → Tamil)
        parts = line.split('\t')
        if len(parts) < 2:
            continue

        src = parts[0].lower()
        tgt = parts[1]

        # Remove punctuation
        src = src.translate(str.maketrans('', '', punctuation))
        tgt = tgt.translate(str.maketrans('', '', punctuation))

        source.append(src)
        target.append(tgt)

except UnicodeDecodeError:
    print("Encoding error in dataset")

# ---------------------------
# CREATE VOCABULARY
# ---------------------------
source_vocab = list(set(' '.join(source)))
if ' ' in source_vocab:
    source_vocab.remove(' ')
source_vocab.insert(0, ' ')

target_vocab = list(set(' '.join(target)))
if ' ' in target_vocab:
    target_vocab.remove(' ')
target_vocab.insert(0, ' ')


source_vocab_len = len(source_vocab)
target_vocab_len = len(target_vocab)

# ---------------------------
# CHARACTER MAPPING
# ---------------------------
source_char_to_int = {char: idx for idx, char in enumerate(source_vocab)}
source_int_to_char = {idx: char for idx, char in enumerate(source_vocab)}
target_char_to_int = {char: idx for idx, char in enumerate(target_vocab)}
target_int_to_char = {idx: char for idx, char in enumerate(target_vocab)}

# ---------------------------
# CONVERT TEXT → INTEGER
# ---------------------------
source = [[source_char_to_int[c] for c in s] for s in source]
target = [[target_char_to_int[c] for c in t] for t in target]

print(source)
print(target)


# ---------------------------
# PADDING
# ---------------------------
m = max(
    max(len(seq) for seq in source),
    max(len(seq) for seq in target)
)
max_sequence_length = max(len(seq) for seq in target)
source_padded = pad_sequences(source, maxlen=m, padding='post')
target_padded = pad_sequences(target, maxlen=max_sequence_length,padding='post')

# ---------------------------
# ONE-HOT ENCODING (TARGET)
# ---------------------------
target_one_hot = []
for seq in target_padded:
 encoded = to_categorical(seq, num_classes=target_vocab_len)
 target_one_hot.append(encoded)
target_one_hot = np.array(target_one_hot)

print(target_one_hot)

# ---------------------------
# MODEL
# ---------------------------
model = Sequential([
    Embedding(source_vocab_len, 64, input_length=m),
    LSTM(128, return_sequences=True),
    Dense(target_vocab_len, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'] )

print(model.summary())

model.fit(source_padded, target_one_hot, epochs=1000)

test_input = np.array([source_padded[9]])

prediction = model.predict(test_input)[0]

output = ""
for i in prediction:
    output += target_int_to_char[np.argmax(i)]

print("Predicted Output:", output.strip())

test_input = np.array([source_padded[19]])

prediction = model.predict(test_input)[0]

output = ""
for i in prediction:
    output += target_int_to_char[np.argmax(i)]

print("Predicted Output:", output.strip())

